### ISSUE TITLE
Unable to get fastify/swagger working with fastify/aws-lambda

### ISSUE THREAD

**Issue by arnabk** [fastify/aws-lambda-fastify#132]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.7.0

### Plugin version

3.1.3

### Node.js version

16.10.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

PopOS 20.04

### Description

Route `/documentations` does not work when used with `@fastify/aws-lambda` and `@fastify/swagger`.

index.ts
```
const awsLambdaFastify = require("@fastify/aws-lambda");
const { fastify } = require('fastify');

const app = fastify({ logger: true });

app.register(require('@fastify/swagger'), {
  routePrefix: '/documentation',
  swagger: {
    info: {
      title: 'Test swagger',
      description: 'Testing the Fastify swagger API',
      version: '0.1.0'
    },
    consumes: ['application/json'],
    produces: ['application/json'],
  },
  uiConfig: {
    docExpansion: 'full',
    deepLinking: false
  },
  exposeRoute: true
});

app.get('/rest', async (request, reply) => {
  return { hello: 'world' }
});

app.ready().then(() => {
  app.swagger();
});

// app.listen({ port: 3000 })

const proxy = awsLambdaFastify(app, {
  callbackWaitsForEmptyEventLoop: false,
  decorateRequest: false,
});
module.exports = {
  handler: proxy,
};

```

serverless.yml
```
service: sls-test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-esbuild
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-north-1

functions:
  rest:
    handler: index.handler
    events:
      - http:
          method: ANY
          path: /{any+}
          cors: true

```

package.json
```
{
  "name": "sls-test",
  "version": "1.0.0",
  "description": "Serverless webpack example using ecma script",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/preset-env": "^7.11.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "^1.6.0",
    "serverless-esbuild": "^1.33.0",
    "serverless-offline": "^11.0.1",
    "serverless-webpack": "^5.3.1",
    "webpack": "^4.35.2"
  },
  "author": "The serverless webpack authors (https://github.com/elastic-coders/serverless-webpack)",
  "license": "MIT",
  "dependencies": {
    "@fastify/aws-lambda": "^3.1.3",
    "@fastify/swagger": "^7.6.1",
    "esbuild": "^0.15.10",
    "fastify": "^4.7.0",
    "server": "^1.0.37"
  }
}
```

### Steps to Reproduce

- Save the above code
- Run `sls offline start` 
- Go to /rest and note that we get valid response
- Go to /documentation and note that it will redirect and get 404

Running the above code as standalone works fine. In order to test this, 
- Uncomment this line
```
app.listen({ port: 3000 })
```
- Comment these lines
```
const proxy = awsLambdaFastify(app, {
  callbackWaitsForEmptyEventLoop: false,
  decorateRequest: false,
});
module.exports = {
  handler: proxy,
};
```
- run `node index.js`
- Go to /rest and note that we get valid response
- Go to /documentation and note that you will be successfully redirected to swagger page

**Comment by adrai** [comment]
Can you please share the received lambda event?

**Comment by adrai** [comment]
add:

```
custom:
  esbuild:
    external:
      - '@fastify/swagger'
```

to your serverless.yml file:

```
service: sls-test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-esbuild
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-north-1

functions:
  rest:
    handler: index.handler
    events:
      - http:
          method: ANY
          path: /{any+}
          cors: true

custom:
  esbuild:
    external:
      - '@fastify/swagger'
```
