### ISSUE TITLE
Doesn't work on a deployed lambda function

### ISSUE THREAD

**Issue by hakimio** [fastify/aws-lambda-fastify#21]
While it seems to work fine when testing locally with `sls offline`, trying to run it on a deployed lambda function with API Gateway, I am getting the following error: 
```json
{
    "errorType": "TypeError",
    "errorMessage": "Cannot convert undefined or null to object",
    "stack": [
        "TypeError: Cannot convert undefined or null to object",
        "    at Function.keys (<anonymous>)",
        "    at getName (/var/task/_optimize/dev-main/src/lambda.js:17374:23)",
        "    at new Plugin (/var/task/_optimize/dev-main/src/lambda.js:17398:15)",
        "    at new Boot (/var/task/_optimize/dev-main/src/lambda.js:16259:16)",
        "    at Boot (/var/task/_optimize/dev-main/src/lambda.js:16211:22)",
        "    at build (/var/task/_optimize/dev-main/src/lambda.js:43616:17)",
        "    at bootstrapServer (/var/task/_optimize/dev-main/src/lambda.js:11:343)",
        "    at Runtime.exports.handler (/var/task/_optimize/dev-main/src/lambda.js:11:617)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
    ]
}
```

## To Reproduce
Here is the `lambda.ts` file used to bootstrap the app:
```ts
import {NestFactory} from '@nestjs/core';
import {FastifyAdapter, NestFastifyApplication} from '@nestjs/platform-fastify';
import {AppModule} from './app.module';
import * as fastify from 'fastify';
import * as awsLambdaFastify from 'aws-lambda-fastify';
import {
    Context,
    APIGatewayProxyEvent,
    APIGatewayProxyResult
} from 'aws-lambda';
import { Logger } from '@nestjs/common';

interface NestApp {
    app: NestFastifyApplication;
    instance: fastify.FastifyInstance;
}

let cachedNestApp: NestApp;

async function bootstrapServer(): Promise<NestApp> {
    const serverOptions: fastify.ServerOptionsAsHttp = {
        logger: true,
    };
    const instance: fastify.FastifyInstance = fastify(serverOptions);
    const app = await NestFactory.create<NestFastifyApplication>(
        AppModule,
        new FastifyAdapter(instance),
        {
            logger: !process.env.AWS_EXECUTION_ENV ? new Logger() : console
        }
    );
    app.setGlobalPrefix(process.env.API_PREFIX);
    await app.init();

    return {
        app,
        instance
    };
}

export const handler = async (
    event: APIGatewayProxyEvent,
    context: Context,
): Promise<APIGatewayProxyResult> => {
    if (!cachedNestApp) {
        cachedNestApp = await bootstrapServer();
    }
    const proxy = awsLambdaFastify(cachedNestApp.instance);

    return proxy(event, context);
};
```

And here is `serverless.yml`:
```yml
service:
  name: my-service

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  common: ${file(../serverless/common.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${self:custom.common.REGION}
  environment:
    API_PREFIX: "${self:custom.common.API_PREFIX}"

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: ${self:custom.common.API_PREFIX}/{proxy+}
```

## Expected behavior

To work without errors.

## Your Environment

- *node version*: 10
- *fastify version*: 2.7.1
